package simple.entity;

import java.io.Serializable;

/**
 * 즐겨찾기 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Favorite implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자. */
	private Users users;

	/** 맛집. */
	private Restaurant restaurant;

	/**
	 * 생성자.
	 */
	public Favorite() {
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 맛집을 설정합니다..
	 * 
	 * @param restaurant
	 *            맛집
	 */
	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	/**
	 * 맛집을 가져옵니다..
	 * 
	 * @return 맛집
	 */
	public Restaurant getRestaurant() {
		return this.restaurant;
	}


}
