package simple.entity;

import java.io.Serializable;

/**
 * 친구 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Friend implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자. */
	private Users users;

	/** 친구아이디. */
	private String friendId;

	/**
	 * 생성자.
	 */
	public Friend() {
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 친구아이디을 설정합니다..
	 * 
	 * @param friendId
	 *            친구아이디
	 */
	public void setFriendId(String friendId) {
		this.friendId = friendId;
	}

	/**
	 * 친구아이디을 가져옵니다..
	 * 
	 * @return 친구아이디
	 */
	public String getFriendId() {
		return this.friendId;
	}


}
