package simple.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 지역 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Location implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 지역이름. */
	private String locaionName;

	/** 관심지역 목록. */
	private Set<FavoriteLocation> favoriteLocationSet;

	/** 맛집게시판 목록. */
	private Set<Restaurants> restaurantsSet;

	/**
	 * 생성자.
	 */
	public Location() {
		this.favoriteLocationSet = new HashSet<FavoriteLocation>();
		this.restaurantsSet = new HashSet<Restaurants>();
	}

	/**
	 * 지역이름을 설정합니다..
	 * 
	 * @param locaionName
	 *            지역이름
	 */
	public void setLocaionName(String locaionName) {
		this.locaionName = locaionName;
	}

	/**
	 * 지역이름을 가져옵니다..
	 * 
	 * @return 지역이름
	 */
	public String getLocaionName() {
		return this.locaionName;
	}

	/**
	 * 관심지역 목록을 설정합니다..
	 * 
	 * @param favoriteLocationSet
	 *            관심지역 목록
	 */
	public void setFavoriteLocationSet(Set<FavoriteLocation> favoriteLocationSet) {
		this.favoriteLocationSet = favoriteLocationSet;
	}

	/**
	 * 관심지역를 추가합니다..
	 * 
	 * @param favoriteLocation
	 *            관심지역
	 */
	public void addFavoriteLocation(FavoriteLocation favoriteLocation) {
		this.favoriteLocationSet.add(favoriteLocation);
	}

	/**
	 * 관심지역 목록을 가져옵니다..
	 * 
	 * @return 관심지역 목록
	 */
	public Set<FavoriteLocation> getFavoriteLocationSet() {
		return this.favoriteLocationSet;
	}

	/**
	 * 맛집게시판 목록을 설정합니다..
	 * 
	 * @param restaurantsSet
	 *            맛집게시판 목록
	 */
	public void setRestaurantsSet(Set<Restaurants> restaurantsSet) {
		this.restaurantsSet = restaurantsSet;
	}

	/**
	 * 맛집게시판를 추가합니다..
	 * 
	 * @param restaurants
	 *            맛집게시판
	 */
	public void addRestaurants(Restaurants restaurants) {
		this.restaurantsSet.add(restaurants);
	}

	/**
	 * 맛집게시판 목록을 가져옵니다..
	 * 
	 * @return 맛집게시판 목록
	 */
	public Set<Restaurants> getRestaurantsSet() {
		return this.restaurantsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((locaionName == null) ? 0 : locaionName.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Location other = (Location) obj;
		if (locaionName == null) {
			if (other.locaionName != null) {
				return false;
			}
		} else if (!locaionName.equals(other.locaionName)) {
			return false;
		}
		return true;
	}

}
