package simple.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 맛집게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Restaurants implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 맛집번호. */
	private Integer restaurantNo;

	/** 맛집이름. */
	private String restaurantName;

	/** 맛집전화번호. */
	private String restaurantNumber;

	/** 맛집평점. */
	private Integer restaurantScore;

	/** 맛집주소. */
	private String restaurantLocation;

	/** 맛집내용. */
	private String restaurantContent;

	/** 사용자. */
	private Users users;

	/** 맛집사진. */
	private String restautantImage;

	/** 지역. */
	private Location location;

	/** 맛집종류. */
	private String restaurantKind;

	/** 댓글게시판 목록. */
	private Set<ReplyBoard> replyBoardSet;

	/** 리뷰게시판 목록. */
	private Set<ReviewBoard> reviewBoardSet;

	/** 즐겨찾기 목록. */
	private Set<Favorite> favoriteSet;

	/**
	 * 생성자.
	 */
	public Restaurants() {
		this.favoriteSet = new HashSet<Favorite>();
		this.replyBoardSet = new HashSet<ReplyBoard>();
		this.reviewBoardSet = new HashSet<ReviewBoard>();
	}

	/**
	 * 맛집번호을 설정합니다..
	 * 
	 * @param restaurantNo
	 *            맛집번호
	 */
	public void setRestaurantNo(Integer restaurantNo) {
		this.restaurantNo = restaurantNo;
	}

	/**
	 * 맛집번호을 가져옵니다..
	 * 
	 * @return 맛집번호
	 */
	public Integer getRestaurantNo() {
		return this.restaurantNo;
	}

	/**
	 * 맛집이름을 설정합니다..
	 * 
	 * @param restaurantName
	 *            맛집이름
	 */
	public void setRestaurantName(String restaurantName) {
		this.restaurantName = restaurantName;
	}

	/**
	 * 맛집이름을 가져옵니다..
	 * 
	 * @return 맛집이름
	 */
	public String getRestaurantName() {
		return this.restaurantName;
	}

	/**
	 * 맛집전화번호을 설정합니다..
	 * 
	 * @param restaurantNumber
	 *            맛집전화번호
	 */
	public void setRestaurantNumber(String restaurantNumber) {
		this.restaurantNumber = restaurantNumber;
	}

	/**
	 * 맛집전화번호을 가져옵니다..
	 * 
	 * @return 맛집전화번호
	 */
	public String getRestaurantNumber() {
		return this.restaurantNumber;
	}

	/**
	 * 맛집평점을 설정합니다..
	 * 
	 * @param restaurantScore
	 *            맛집평점
	 */
	public void setRestaurantScore(Integer restaurantScore) {
		this.restaurantScore = restaurantScore;
	}

	/**
	 * 맛집평점을 가져옵니다..
	 * 
	 * @return 맛집평점
	 */
	public Integer getRestaurantScore() {
		return this.restaurantScore;
	}

	/**
	 * 맛집주소을 설정합니다..
	 * 
	 * @param restaurantLocation
	 *            맛집주소
	 */
	public void setRestaurantLocation(String restaurantLocation) {
		this.restaurantLocation = restaurantLocation;
	}

	/**
	 * 맛집주소을 가져옵니다..
	 * 
	 * @return 맛집주소
	 */
	public String getRestaurantLocation() {
		return this.restaurantLocation;
	}

	/**
	 * 맛집내용을 설정합니다..
	 * 
	 * @param restaurantContent
	 *            맛집내용
	 */
	public void setRestaurantContent(String restaurantContent) {
		this.restaurantContent = restaurantContent;
	}

	/**
	 * 맛집내용을 가져옵니다..
	 * 
	 * @return 맛집내용
	 */
	public String getRestaurantContent() {
		return this.restaurantContent;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 맛집사진을 설정합니다..
	 * 
	 * @param restautantImage
	 *            맛집사진
	 */
	public void setRestautantImage(String restautantImage) {
		this.restautantImage = restautantImage;
	}

	/**
	 * 맛집사진을 가져옵니다..
	 * 
	 * @return 맛집사진
	 */
	public String getRestautantImage() {
		return this.restautantImage;
	}

	/**
	 * 지역을 설정합니다..
	 * 
	 * @param location
	 *            지역
	 */
	public void setLocation(Location location) {
		this.location = location;
	}

	/**
	 * 지역을 가져옵니다..
	 * 
	 * @return 지역
	 */
	public Location getLocation() {
		return this.location;
	}

	/**
	 * 맛집종류을 설정합니다..
	 * 
	 * @param restaurantKind
	 *            맛집종류
	 */
	public void setRestaurantKind(String restaurantKind) {
		this.restaurantKind = restaurantKind;
	}

	/**
	 * 맛집종류을 가져옵니다..
	 * 
	 * @return 맛집종류
	 */
	public String getRestaurantKind() {
		return this.restaurantKind;
	}

	/**
	 * 댓글게시판 목록을 설정합니다..
	 * 
	 * @param replyBoardSet
	 *            댓글게시판 목록
	 */
	public void setReplyBoardSet(Set<ReplyBoard> replyBoardSet) {
		this.replyBoardSet = replyBoardSet;
	}

	/**
	 * 댓글게시판를 추가합니다..
	 * 
	 * @param replyBoard
	 *            댓글게시판
	 */
	public void addReplyBoard(ReplyBoard replyBoard) {
		this.replyBoardSet.add(replyBoard);
	}

	/**
	 * 댓글게시판 목록을 가져옵니다..
	 * 
	 * @return 댓글게시판 목록
	 */
	public Set<ReplyBoard> getReplyBoardSet() {
		return this.replyBoardSet;
	}

	/**
	 * 리뷰게시판 목록을 설정합니다..
	 * 
	 * @param reviewBoardSet
	 *            리뷰게시판 목록
	 */
	public void setReviewBoardSet(Set<ReviewBoard> reviewBoardSet) {
		this.reviewBoardSet = reviewBoardSet;
	}

	/**
	 * 리뷰게시판를 추가합니다..
	 * 
	 * @param reviewBoard
	 *            리뷰게시판
	 */
	public void addReviewBoard(ReviewBoard reviewBoard) {
		this.reviewBoardSet.add(reviewBoard);
	}

	/**
	 * 리뷰게시판 목록을 가져옵니다..
	 * 
	 * @return 리뷰게시판 목록
	 */
	public Set<ReviewBoard> getReviewBoardSet() {
		return this.reviewBoardSet;
	}

	/**
	 * 즐겨찾기 목록을 설정합니다..
	 * 
	 * @param favoriteSet
	 *            즐겨찾기 목록
	 */
	public void setFavoriteSet(Set<Favorite> favoriteSet) {
		this.favoriteSet = favoriteSet;
	}

	/**
	 * 즐겨찾기를 추가합니다..
	 * 
	 * @param favorite
	 *            즐겨찾기
	 */
	public void addFavorite(Favorite favorite) {
		this.favoriteSet.add(favorite);
	}

	/**
	 * 즐겨찾기 목록을 가져옵니다..
	 * 
	 * @return 즐겨찾기 목록
	 */
	public Set<Favorite> getFavoriteSet() {
		return this.favoriteSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((restaurantNo == null) ? 0 : restaurantNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Restaurants other = (Restaurants) obj;
		if (restaurantNo == null) {
			if (other.restaurantNo != null) {
				return false;
			}
		} else if (!restaurantNo.equals(other.restaurantNo)) {
			return false;
		}
		return true;
	}

}
