package entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Boards implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시글 번호. */
	private Integer boardsNo;

	/** 게시글제목. */
	private String boardsTitle;

	/** 게시글내용. */
	private String boardsContent;

	/** 게시글작성일. */
	private Date boardsDate;

	/** 게시글종류. */
	private String boardsType;

	/** 사용자. */
	private Users users;

	/** 게시글댓글 목록. */
	private Set<Replys> replysSet;

	/**
	 * 생성자.
	 */
	public Boards() {
		this.replysSet = new HashSet<Replys>();
	}

	/**
	 * 게시글 번호을 설정합니다..
	 * 
	 * @param boardsNo
	 *            게시글 번호
	 */
	public void setBoardsNo(Integer boardsNo) {
		this.boardsNo = boardsNo;
	}

	/**
	 * 게시글 번호을 가져옵니다..
	 * 
	 * @return 게시글 번호
	 */
	public Integer getBoardsNo() {
		return this.boardsNo;
	}

	/**
	 * 게시글제목을 설정합니다..
	 * 
	 * @param boardsTitle
	 *            게시글제목
	 */
	public void setBoardsTitle(String boardsTitle) {
		this.boardsTitle = boardsTitle;
	}

	/**
	 * 게시글제목을 가져옵니다..
	 * 
	 * @return 게시글제목
	 */
	public String getBoardsTitle() {
		return this.boardsTitle;
	}

	/**
	 * 게시글내용을 설정합니다..
	 * 
	 * @param boardsContent
	 *            게시글내용
	 */
	public void setBoardsContent(String boardsContent) {
		this.boardsContent = boardsContent;
	}

	/**
	 * 게시글내용을 가져옵니다..
	 * 
	 * @return 게시글내용
	 */
	public String getBoardsContent() {
		return this.boardsContent;
	}

	/**
	 * 게시글작성일을 설정합니다..
	 * 
	 * @param boardsDate
	 *            게시글작성일
	 */
	public void setBoardsDate(Date boardsDate) {
		this.boardsDate = boardsDate;
	}

	/**
	 * 게시글작성일을 가져옵니다..
	 * 
	 * @return 게시글작성일
	 */
	public Date getBoardsDate() {
		return this.boardsDate;
	}

	/**
	 * 게시글종류을 설정합니다..
	 * 
	 * @param boardsType
	 *            게시글종류
	 */
	public void setBoardsType(String boardsType) {
		this.boardsType = boardsType;
	}

	/**
	 * 게시글종류을 가져옵니다..
	 * 
	 * @return 게시글종류
	 */
	public String getBoardsType() {
		return this.boardsType;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 게시글댓글 목록을 설정합니다..
	 * 
	 * @param replysSet
	 *            게시글댓글 목록
	 */
	public void setReplysSet(Set<Replys> replysSet) {
		this.replysSet = replysSet;
	}

	/**
	 * 게시글댓글를 추가합니다..
	 * 
	 * @param replys
	 *            게시글댓글
	 */
	public void addReplys(Replys replys) {
		this.replysSet.add(replys);
	}

	/**
	 * 게시글댓글 목록을 가져옵니다..
	 * 
	 * @return 게시글댓글 목록
	 */
	public Set<Replys> getReplysSet() {
		return this.replysSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boardsNo == null) ? 0 : boardsNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Boards other = (Boards) obj;
		if (boardsNo == null) {
			if (other.boardsNo != null) {
				return false;
			}
		} else if (!boardsNo.equals(other.boardsNo)) {
			return false;
		}
		return true;
	}

}
