package entity;

import java.io.Serializable;

/**
 * 자격증취득회원 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class LicensedUser implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자. */
	private Users users;

	/** 자격증. */
	private License license;

	/**
	 * 생성자.
	 */
	public LicensedUser() {
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 자격증을 설정합니다..
	 * 
	 * @param license
	 *            자격증
	 */
	public void setLicense(License license) {
		this.license = license;
	}

	/**
	 * 자격증을 가져옵니다..
	 * 
	 * @return 자격증
	 */
	public License getLicense() {
		return this.license;
	}


}
