package entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 쪽지 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Message implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 메세지 번호. */
	private Integer messageNo;

	/** 받는사람. */
	private String reciever;

	/** 보내는사람. */
	private String sender;

	/** 메세지내용. */
	private String messageContent;

	/** 작성날짜. */
	private Date writeDate;

	/** 신고여부및분류. */
	private String warnCheck;

	/** 신고글 번호. */
	private Integer warnNo;

	/**
	 * 생성자.
	 */
	public Message() {
	}

	/**
	 * 메세지 번호을 설정합니다..
	 * 
	 * @param messageNo
	 *            메세지 번호
	 */
	public void setMessageNo(Integer messageNo) {
		this.messageNo = messageNo;
	}

	/**
	 * 메세지 번호을 가져옵니다..
	 * 
	 * @return 메세지 번호
	 */
	public Integer getMessageNo() {
		return this.messageNo;
	}

	/**
	 * 받는사람을 설정합니다..
	 * 
	 * @param reciever
	 *            받는사람
	 */
	public void setReciever(String reciever) {
		this.reciever = reciever;
	}

	/**
	 * 받는사람을 가져옵니다..
	 * 
	 * @return 받는사람
	 */
	public String getReciever() {
		return this.reciever;
	}

	/**
	 * 보내는사람을 설정합니다..
	 * 
	 * @param sender
	 *            보내는사람
	 */
	public void setSender(String sender) {
		this.sender = sender;
	}

	/**
	 * 보내는사람을 가져옵니다..
	 * 
	 * @return 보내는사람
	 */
	public String getSender() {
		return this.sender;
	}

	/**
	 * 메세지내용을 설정합니다..
	 * 
	 * @param messageContent
	 *            메세지내용
	 */
	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	/**
	 * 메세지내용을 가져옵니다..
	 * 
	 * @return 메세지내용
	 */
	public String getMessageContent() {
		return this.messageContent;
	}

	/**
	 * 작성날짜을 설정합니다..
	 * 
	 * @param writeDate
	 *            작성날짜
	 */
	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	/**
	 * 작성날짜을 가져옵니다..
	 * 
	 * @return 작성날짜
	 */
	public Date getWriteDate() {
		return this.writeDate;
	}

	/**
	 * 신고여부및분류을 설정합니다..
	 * 
	 * @param warnCheck
	 *            신고여부및분류
	 */
	public void setWarnCheck(String warnCheck) {
		this.warnCheck = warnCheck;
	}

	/**
	 * 신고여부및분류을 가져옵니다..
	 * 
	 * @return 신고여부및분류
	 */
	public String getWarnCheck() {
		return this.warnCheck;
	}

	/**
	 * 신고글 번호을 설정합니다..
	 * 
	 * @param warnNo
	 *            신고글 번호
	 */
	public void setWarnNo(Integer warnNo) {
		this.warnNo = warnNo;
	}

	/**
	 * 신고글 번호을 가져옵니다..
	 * 
	 * @return 신고글 번호
	 */
	public Integer getWarnNo() {
		return this.warnNo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((messageNo == null) ? 0 : messageNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Message other = (Message) obj;
		if (messageNo == null) {
			if (other.messageNo != null) {
				return false;
			}
		} else if (!messageNo.equals(other.messageNo)) {
			return false;
		}
		return true;
	}

}
