package mybabthis.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Breply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글번호. */
	private Integer breplyNo;

	/** 댓글내용. */
	private String breplyContent;

	/** 댓글작성일. */
	private Date breplyRegdate;

	/** 댓글수정일. */
	private Date breplyUpdatedate;

	/** 사용자. */
	private Users users;

	/** 게시판. */
	private Board board;
	
	
	
	
	/** 외래키 ******************/
	private String userId;
	private Integer boardNo;
	public void setUserId(String userId){
		this.userId=userId;
	}
	public String getUserId(){
		return this.userId;
	}
	public void setBoardNo(Integer boardNo){
		this.boardNo=boardNo;
	}
	public Integer getBoardNo(){
		return this.boardNo;
	}
	/** 외래키 ******************/

	/**
	 * 생성자.
	 */
	public Breply() {
	}

	/**
	 * 댓글번호을 설정합니다..
	 * 
	 * @param breplyNo
	 *            댓글번호
	 */
	public void setBreplyNo(Integer breplyNo) {
		this.breplyNo = breplyNo;
	}

	/**
	 * 댓글번호을 가져옵니다..
	 * 
	 * @return 댓글번호
	 */
	public Integer getBreplyNo() {
		return this.breplyNo;
	}

	/**
	 * 댓글내용을 설정합니다..
	 * 
	 * @param breplyContent
	 *            댓글내용
	 */
	public void setBreplyContent(String breplyContent) {
		this.breplyContent = breplyContent;
	}

	/**
	 * 댓글내용을 가져옵니다..
	 * 
	 * @return 댓글내용
	 */
	public String getBreplyContent() {
		return this.breplyContent;
	}

	/**
	 * 댓글작성일을 설정합니다..
	 * 
	 * @param breplyRegdate
	 *            댓글작성일
	 */
	public void setBreplyRegdate(Date breplyRegdate) {
		this.breplyRegdate = breplyRegdate;
	}

	/**
	 * 댓글작성일을 가져옵니다..
	 * 
	 * @return 댓글작성일
	 */
	public Date getBreplyRegdate() {
		return this.breplyRegdate;
	}

	/**
	 * 댓글수정일을 설정합니다..
	 * 
	 * @param breplyUpdatedate
	 *            댓글수정일
	 */
	public void setBreplyUpdatedate(Date breplyUpdatedate) {
		this.breplyUpdatedate = breplyUpdatedate;
	}

	/**
	 * 댓글수정일을 가져옵니다..
	 * 
	 * @return 댓글수정일
	 */
	public Date getBreplyUpdatedate() {
		return this.breplyUpdatedate;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 게시판을 설정합니다..
	 * 
	 * @param board
	 *            게시판
	 */
	public void setBoard(Board board) {
		this.board = board;
	}

	/**
	 * 게시판을 가져옵니다..
	 * 
	 * @return 게시판
	 */
	public Board getBoard() {
		return this.board;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((breplyNo == null) ? 0 : breplyNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Breply other = (Breply) obj;
		if (breplyNo == null) {
			if (other.breplyNo != null) {
				return false;
			}
		} else if (!breplyNo.equals(other.breplyNo)) {
			return false;
		}
		return true;
	}

}
