package mybabthis.entity;

import java.io.Serializable;

/**
 * 관심지역 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FavoriteLocation implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자. */
	private Users users;

	/** 지역. */
	private Loc loc;

	/**
	 * 생성자.
	 */
	public FavoriteLocation() {
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 지역을 설정합니다..
	 * 
	 * @param loc
	 *            지역
	 */
	public void setLoc(Loc loc) {
		this.loc = loc;
	}

	/**
	 * 지역을 가져옵니다..
	 * 
	 * @return 지역
	 */
	public Loc getLoc() {
		return this.loc;
	}


}
