package mybabthis.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 자격증 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class License implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 자격증번호. */
	private Integer licenseNo;

	/** 게시글수. */
	private Integer writeCnt;

	/** 지역이름. */
	private String locName;

	/** 맛집종류. */
	private String resKind;

	/** 자격증취득회원 목록. */
	private Set<LicensedUser> licensedUserSet;

	/**
	 * 생성자.
	 */
	public License() {
		this.licensedUserSet = new HashSet<LicensedUser>();
	}

	/**
	 * 자격증번호을 설정합니다..
	 * 
	 * @param licenseNo
	 *            자격증번호
	 */
	public void setLicenseNo(Integer licenseNo) {
		this.licenseNo = licenseNo;
	}

	/**
	 * 자격증번호을 가져옵니다..
	 * 
	 * @return 자격증번호
	 */
	public Integer getLicenseNo() {
		return this.licenseNo;
	}

	/**
	 * 게시글수을 설정합니다..
	 * 
	 * @param writeCnt
	 *            게시글수
	 */
	public void setWriteCnt(Integer writeCnt) {
		this.writeCnt = writeCnt;
	}

	/**
	 * 게시글수을 가져옵니다..
	 * 
	 * @return 게시글수
	 */
	public Integer getWriteCnt() {
		return this.writeCnt;
	}

	/**
	 * 지역이름을 설정합니다..
	 * 
	 * @param locName
	 *            지역이름
	 */
	public void setLocName(String locName) {
		this.locName = locName;
	}

	/**
	 * 지역이름을 가져옵니다..
	 * 
	 * @return 지역이름
	 */
	public String getLocName() {
		return this.locName;
	}

	/**
	 * 맛집종류을 설정합니다..
	 * 
	 * @param resKind
	 *            맛집종류
	 */
	public void setResKind(String resKind) {
		this.resKind = resKind;
	}

	/**
	 * 맛집종류을 가져옵니다..
	 * 
	 * @return 맛집종류
	 */
	public String getResKind() {
		return this.resKind;
	}

	/**
	 * 자격증취득회원 목록을 설정합니다..
	 * 
	 * @param licensedUserSet
	 *            자격증취득회원 목록
	 */
	public void setLicensedUserSet(Set<LicensedUser> licensedUserSet) {
		this.licensedUserSet = licensedUserSet;
	}

	/**
	 * 자격증취득회원를 추가합니다..
	 * 
	 * @param licensedUser
	 *            자격증취득회원
	 */
	public void addLicensedUser(LicensedUser licensedUser) {
		this.licensedUserSet.add(licensedUser);
	}

	/**
	 * 자격증취득회원 목록을 가져옵니다..
	 * 
	 * @return 자격증취득회원 목록
	 */
	public Set<LicensedUser> getLicensedUserSet() {
		return this.licensedUserSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((licenseNo == null) ? 0 : licenseNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		License other = (License) obj;
		if (licenseNo == null) {
			if (other.licenseNo != null) {
				return false;
			}
		} else if (!licenseNo.equals(other.licenseNo)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "License [licenseNo=" + licenseNo + ", writeCnt=" + writeCnt
				+ ", locName=" + locName + ", resKind=" + resKind
				+ ", licensedUserSet=" + licensedUserSet + "]";
	}

	
	
	
}
