package mybabthis.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 지역 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Loc implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 지역이름. */
	private String locName;

	/** 맛집 목록. */
	private Set<Restaurant> restaurantSet;

	/** 관심지역 목록. */
	private Set<FavoriteLocation> favoriteLocationSet;

	/**
	 * 생성자.
	 */
	public Loc() {
		this.favoriteLocationSet = new HashSet<FavoriteLocation>();
		this.restaurantSet = new HashSet<Restaurant>();
	}

	/**
	 * 지역이름을 설정합니다..
	 * 
	 * @param locName
	 *            지역이름
	 */
	public void setLocName(String locName) {
		this.locName = locName;
	}

	/**
	 * 지역이름을 가져옵니다..
	 * 
	 * @return 지역이름
	 */
	public String getLocName() {
		return this.locName;
	}

	/**
	 * 맛집 목록을 설정합니다..
	 * 
	 * @param restaurantSet
	 *            맛집 목록
	 */
	public void setRestaurantSet(Set<Restaurant> restaurantSet) {
		this.restaurantSet = restaurantSet;
	}

	/**
	 * 맛집를 추가합니다..
	 * 
	 * @param restaurant
	 *            맛집
	 */
	public void addRestaurant(Restaurant restaurant) {
		this.restaurantSet.add(restaurant);
	}

	/**
	 * 맛집 목록을 가져옵니다..
	 * 
	 * @return 맛집 목록
	 */
	public Set<Restaurant> getRestaurantSet() {
		return this.restaurantSet;
	}

	/**
	 * 관심지역 목록을 설정합니다..
	 * 
	 * @param favoriteLocationSet
	 *            관심지역 목록
	 */
	public void setFavoriteLocationSet(Set<FavoriteLocation> favoriteLocationSet) {
		this.favoriteLocationSet = favoriteLocationSet;
	}

	/**
	 * 관심지역를 추가합니다..
	 * 
	 * @param favoriteLocation
	 *            관심지역
	 */
	public void addFavoriteLocation(FavoriteLocation favoriteLocation) {
		this.favoriteLocationSet.add(favoriteLocation);
	}

	/**
	 * 관심지역 목록을 가져옵니다..
	 * 
	 * @return 관심지역 목록
	 */
	public Set<FavoriteLocation> getFavoriteLocationSet() {
		return this.favoriteLocationSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((locName == null) ? 0 : locName.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Loc other = (Loc) obj;
		if (locName == null) {
			if (other.locName != null) {
				return false;
			}
		} else if (!locName.equals(other.locName)) {
			return false;
		}
		return true;
	}

}
