package mybabthis.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 쪽지 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Msg implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 메세지 번호. */
	private Integer msgNo;

	/** 받는사람. */
	private String receiver;

	/** 보내는사람. */
	private String sender;

	/** 메세지내용. */
	private String msgContent;

	/** 작성날짜. */
	private Date writeDate;

	/** 신고여부및분류. */
	private String writeType;

	/** 신고글 번호. */
	private Integer warnNo;

	/**
	 * 생성자.
	 */
	public Msg() {
	}

	/**
	 * 메세지 번호을 설정합니다..
	 * 
	 * @param msgNo
	 *            메세지 번호
	 */
	public void setMsgNo(Integer msgNo) {
		this.msgNo = msgNo;
	}

	/**
	 * 메세지 번호을 가져옵니다..
	 * 
	 * @return 메세지 번호
	 */
	public Integer getMsgNo() {
		return this.msgNo;
	}

	/**
	 * 받는사람을 설정합니다..
	 * 
	 * @param reciever
	 *            받는사람
	 */
	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	/**
	 * 받는사람을 가져옵니다..
	 * 
	 * @return 받는사람
	 */
	public String getReceiver() {
		return this.receiver;
	}

	/**
	 * 보내는사람을 설정합니다..
	 * 
	 * @param sender
	 *            보내는사람
	 */
	public void setSender(String sender) {
		this.sender = sender;
	}

	/**
	 * 보내는사람을 가져옵니다..
	 * 
	 * @return 보내는사람
	 */
	public String getSender() {
		return this.sender;
	}

	/**
	 * 메세지내용을 설정합니다..
	 * 
	 * @param msgContent
	 *            메세지내용
	 */
	public void setMsgContent(String msgContent) {
		this.msgContent = msgContent;
	}

	/**
	 * 메세지내용을 가져옵니다..
	 * 
	 * @return 메세지내용
	 */
	public String getMsgContent() {
		return this.msgContent;
	}

	/**
	 * 작성날짜을 설정합니다..
	 * 
	 * @param writeDate
	 *            작성날짜
	 */
	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	/**
	 * 작성날짜을 가져옵니다..
	 * 
	 * @return 작성날짜
	 */
	public Date getWriteDate() {
		return this.writeDate;
	}

	/**
	 * 신고여부및분류을 설정합니다..
	 * 
	 * @param writeType
	 *            신고여부및분류
	 */
	public void setWriteType(String writeType) {
		this.writeType = writeType;
	}

	/**
	 * 신고여부및분류을 가져옵니다..
	 * 
	 * @return 신고여부및분류
	 */
	public String getWriteType() {
		return this.writeType;
	}

	/**
	 * 신고글 번호을 설정합니다..
	 * 
	 * @param warnNo
	 *            신고글 번호
	 */
	public void setWarnNo(Integer warnNo) {
		this.warnNo = warnNo;
	}

	/**
	 * 신고글 번호을 가져옵니다..
	 * 
	 * @return 신고글 번호
	 */
	public Integer getWarnNo() {
		return this.warnNo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((msgNo == null) ? 0 : msgNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Msg other = (Msg) obj;
		if (msgNo == null) {
			if (other.msgNo != null) {
				return false;
			}
		} else if (!msgNo.equals(other.msgNo)) {
			return false;
		}
		return true;
	}

}
