package mybabthis.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 맛집댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Resreply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글번호. */
	private Integer resreplyNo;

	/** 댓글내용. */
	private String resreplyContent;

	/** 작성날짜. */
	private Date resreplyRegdate;

	/** 수정날짜. */
	private Date resreplyUpdatedate;

	/** 맛집. */
	private Restaurant restaurant;

	/** 사용자. */
	private Users users;

	/**
	 * 생성자.
	 */
	public Resreply() {
	}

	/**
	 * 댓글번호을 설정합니다..
	 * 
	 * @param resreplyNo
	 *            댓글번호
	 */
	public void setResreplyNo(Integer resreplyNo) {
		this.resreplyNo = resreplyNo;
	}

	/**
	 * 댓글번호을 가져옵니다..
	 * 
	 * @return 댓글번호
	 */
	public Integer getResreplyNo() {
		return this.resreplyNo;
	}

	/**
	 * 댓글내용을 설정합니다..
	 * 
	 * @param resreplyContent
	 *            댓글내용
	 */
	public void setResreplyContent(String resreplyContent) {
		this.resreplyContent = resreplyContent;
	}

	/**
	 * 댓글내용을 가져옵니다..
	 * 
	 * @return 댓글내용
	 */
	public String getResreplyContent() {
		return this.resreplyContent;
	}

	/**
	 * 작성날짜을 설정합니다..
	 * 
	 * @param resreplyRegdate
	 *            작성날짜
	 */
	public void setResreplyRegdate(Date resreplyRegdate) {
		this.resreplyRegdate = resreplyRegdate;
	}

	/**
	 * 작성날짜을 가져옵니다..
	 * 
	 * @return 작성날짜
	 */
	public Date getResreplyRegdate() {
		return this.resreplyRegdate;
	}

	/**
	 * 수정날짜을 설정합니다..
	 * 
	 * @param resreplyUpdatedate
	 *            수정날짜
	 */
	public void setResreplyUpdatedate(Date resreplyUpdatedate) {
		this.resreplyUpdatedate = resreplyUpdatedate;
	}

	/**
	 * 수정날짜을 가져옵니다..
	 * 
	 * @return 수정날짜
	 */
	public Date getResreplyUpdatedate() {
		return this.resreplyUpdatedate;
	}

	/**
	 * 맛집을 설정합니다..
	 * 
	 * @param restaurant
	 *            맛집
	 */
	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	/**
	 * 맛집을 가져옵니다..
	 * 
	 * @return 맛집
	 */
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((resreplyNo == null) ? 0 : resreplyNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Resreply other = (Resreply) obj;
		if (resreplyNo == null) {
			if (other.resreplyNo != null) {
				return false;
			}
		} else if (!resreplyNo.equals(other.resreplyNo)) {
			return false;
		}
		return true;
	}

}
